apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-frontend
  name: udagram-frontend-svc
spec:
  ports:
  - name: "8100"
    port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: udagram-frontend
  type: LoadBalancer
